# This workflow runs the `check_install` script with a few different versions of Python to make sure everything's in order.
# Based on: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python version sanity check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Make dummy empty lab dir
      run: mkdir -p ../labs
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        python check_install.py
